
server.port=8080

spring.application.name=secure-access-control-service

# MONGODB CONFIG
# Replace with your MongoDB connection string
spring.data.mongodb.uri=${MONGO_URI}

# If using custom MongoConfig, keep this
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
#JWT Secret
# Replace with your secure secret key (minimum 256-bit recommended)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Logging
logging.level.org.springframework=INFO
logging.level.com.project.security=DEBUG

# Validation / Error
server.error.include-message=always
server.error.include-binding-errors=always